# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getThreads <- function() {
    .Call(`_focr_getThreads`)
}

setThreads <- function(n, reset_after_fork) {
    .Call(`_focr_setThreads`, n, reset_after_fork)
}

pis_2D <- function(pval, dim1, dim2, tau = 0.1, h = 10.0, verbose = 0L) {
    .Call(`_focr_pis_2D`, pval, dim1, dim2, tau, h, verbose)
}

sumsquared <- function(x) {
    .Call(`_focr_sumsquared`, x)
}

fastcov <- function(x, col1, col2) {
    .Call(`_focr_fastcov`, x, col1, col2)
}

